[[purgecss]]
css = "pages/global.css"
content = ["templates/base.html", ".build/production/global.js"]

[[purgecss]]
css = "pages/index.css"
content = ["templates/index.html"]

[[purgecss]]
css = "pages/agency.css"
content = ["templates/agency.html"]

[[purgecss]]
css = "pages/portfolio.css"
content = ["templates/portfolio.html"]

[[purgecss]]
css = "pages/contact.css"
content = ["templates/contact.html"]

[[purgecss]]
css = "components/swiper.css"
content = ["templates/agency.html", "templates/index.html", ".build/production/swiper.js"]

[[purgecss]]
css = "pages/onepage.css"
content = ["templates/showcase_website.html"]

[[purgecss]]
css = "pages/legals.css"
content = ["templates/legals.html"]