[[purgecss]]
css = "global.css"
content = ["templates/base.html", ".build/production/js/global.js"]
safelist = ["webp_supportted", "no_webp", "navbar show", "read_more"]

[[purgecss]]
css = "pages/index.css"
content = ["templates/pages/index.html", ".build/production/js/index.js"]
safelist = [
    "webp_supportted",
    "no_webp",
    "carousel__pagination__item",
    "carousel__pagination__item--current",
    "carousel__pagination__item--hidden",
    "video-actions--ended",
    "video-actions--played",
    "video-actions--hide"
]

[[purgecss]]
css = "pages/agency.css"
content = ["templates/pages/agency.html", "templates/components/employee.html"]
safelist = ["webp_supportted", "no_webp", "carousel__pagination__item", "carousel__pagination__item--current", "carousel__pagination__item--hidden"]

[[purgecss]]
css = "pages/portfolio.css"
content = ["templates/portfolio/index.html", "templates/components/project.html"]
safelist = ["webp_supportted", "no_webp"]

[[purgecss]]
css = "pages/project.css"
content = ["templates/portfolio/project.html"]
safelist = ["lightbox", "lightbox--active", "carousel__pagination__item", "carousel__pagination__item--current", "carousel__pagination__item--hidden"]

[[purgecss]]
css = "pages/contact.css"
content = ["templates/pages/contact.html", ".build/production/js/contact.js"]
safelist = ["webp_supportted", "no_webp", "carousel__pagination__item", "carousel__pagination__item--current", "carousel__pagination__item index", "carousel__pagination__item descr"]

[[purgecss]]
css = "pages/onepage.css"
content = ["templates/pages/showcase_website.html", "templates/onepage.html", "templates/e_commerce.html", ".build/production/js/global.js"]
safelist = ["webp_supportted", "no_webp"]

[[purgecss]]
css = "pages/legals.css"
content = ["templates/pages/legals.html"]

[[purgecss]]
css = "pages/404.css"
content = ["templates/pages/404.html"]

[[purgecss]]
css = "pages/faq.css"
content = ["templates/pages/faq.html"]
safelist = ["aria-expanded"]

[[purgecss]]
css = "pages/website_creation.css"
content = ["webp_supportted", "templates/pages/website_creation.html", ".build/production/js/global.js", ".build/production/js/website_creation.js"]
safelist = ["carousel__pagination__item", "carousel__pagination__item--current", "carousel__pagination__item index", "carousel__pagination__item descr"]